"use strict";
const fs = require("fs");
const path = require("path");

function parsePBS(file) {
  const text = fs.readFileSync(file, "utf8").split(/\r?\n/);
  const out = Object.create(null);
  let cur = null;

  for (const raw of text) {
    const line = raw.replace(/^\uFEFF/, "").trim();
    if (!line || line.startsWith("#")) continue;

    const m = line.match(/^\[([^\]]+)\]$/);
    if (m) {
      cur = m[1];
      out[cur] = Object.create(null);
      continue;
    }
    if (!cur) continue;

    const i = line.indexOf("=");
    if (i < 0) continue;

    const k = line.slice(0, i).trim();
    const v = line.slice(i + 1).trim();
    out[cur][k] = v;
  }

  return out;
}

// Merge por campo: si existe el mismo header, solo pisa keys sueltas (Abilities, etc.)
function mergePBS(baseObj, customObj) {
  for (const header of Object.keys(customObj)) {
    if (!baseObj[header]) baseObj[header] = Object.create(null);
    Object.assign(baseObj[header], customObj[header]); // pisa solo keys
  }
  return baseObj;
}

function writeTS(outFile, exportName, obj) {
  const header =
`/* AUTO-GENERATED FILE. DO NOT EDIT BY HAND.
   Generated by generate-pbs.js from PBS txt files. */
`;
  const body =
`${header}
export const ${exportName}: Record<string, Record<string, string>> = ${JSON.stringify(obj, null, 2)};
`;
  fs.mkdirSync(path.dirname(outFile), {recursive: true});
  fs.writeFileSync(outFile, body, "utf8");
}

const root = process.cwd();

// Oficiales
const inBase = path.resolve(root, "data", "pokemon.txt");
const inForms = path.resolve(root, "data", "pokemon_forms.txt");

// Custom opcionales (pisan oficiales)
const inBaseCustom = path.resolve(root, "data", "pokemon_custom.txt");
const inFormsCustom = path.resolve(root, "data", "pokemon_forms_custom.txt");

const baseObj = parsePBS(inBase);
const formsObj = parsePBS(inForms);

if (fs.existsSync(inBaseCustom)) {
  const baseCustomObj = parsePBS(inBaseCustom);
  mergePBS(baseObj, baseCustomObj);
}

if (fs.existsSync(inFormsCustom)) {
  const formsCustomObj = parsePBS(inFormsCustom);
  mergePBS(formsObj, formsCustomObj);
}

writeTS(path.resolve(root, "data", "pokemon-pbs.ts"), "basePBS", baseObj);
writeTS(path.resolve(root, "data", "pokemon-forms-pbs.ts"), "formsPBS", formsObj);

console.log("OK: wrote data/pokemon-pbs.ts and data/pokemon-forms-pbs.ts (with optional custom overrides)");